\c d5elro0khve1bc;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR (80) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS addresses (
  id SERIAL PRIMARY KEY,
  full_address text NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE
);
