\c d5elro0khve1bc;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(40) PRIMARY KEY UNIQUE
);

CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP DEFAULT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  description VARCHAR (300) NOT NULL,
  user_id VARCHAR(40) NOT NULL REFERENCES users ON DELETE CASCADE
);
